tests/torch/test_hybrid_converter.py
should fix the gpt2 test now using the default p_error = 2^-40 instead of 0.01.
=> chore: remove randomness from gpt2 hybrid test

src/concrete/ml/quantization/quantizers.py, src/concrete/ml/sklearn/__init__.py, src/concrete/ml/sklearn/base.py, tests/sklearn/test_sklearn_models.py
when re-fitting linear models, quantizers were appended to a list without ever being used. As for tree-baeed models, we now re-compute them at each fit
closes [zama-ai/concrete-ml-internal/issues/#3865](https://github.com/zama-ai/concrete-ml-internal/issues/3865)
=> fix: re-compute quantization params when re-fitting linear models

.github/CODEOWNERS
closes https://github.com/zama-ai/concrete-ml-internal/issues/3872
=> chore: add all team members as code owners

Makefile, script/doc_utils/check_no_gitbook_links.sh, script/make_utils/check_internal_links.sh
We no longer have two `check_links` as the repository is now public (therefore, most links as well)
closes https://github.com/zama-ai/concrete-ml-internal/issues/3881
=> chore: improve make check_links

.github/workflows/continuous-integration.yaml
Now that we have a workflow to force pushes public main to internal main we want to avoid running the CI twice. We can skip it directly in the workflow.
=> chore: disable CI if internal and push to main

Makefile, script/release_utils/check_branch_name.sh
For a release of version `a.b.c`, the branch name is expected to be `release/a.b.x`
closes https://github.com/zama-ai/concrete-ml-internal/issues/1957
=> chore: check branch name format when releasing

.github/workflows/continuous-integration.yaml
Now that internal main is synced with public main on all pushes to public main and that internal main CI is not launched we also want it to not crash in this case.
Hopefully this commits fixes that.
=> chore: avoid crashing internal CI if skipped on main

.github/workflows/continuous-integration.yaml
Basically, this will make regular CIs (from PRs) skip unnecessary checks (like running pytest for documentation-only PRs) !
refs https://github.com/zama-ai/concrete-ml-internal/issues/3893
closes https://github.com/zama-ai/concrete-ml-internal/issues/2870
=> chore: skip steps in regular CIs if possible

Makefile
Collecting tests was enough for triggering the parameter search flaky error, so I moved it out of `pytest_no_flaky`
=> chore: move collection of flaky tests out of pytest_no_flaky

tests/sklearn/test_sklearn_models.py
\#3389 was previously flaky but updates in Concrete fixed the issue. We can now safely remove the skip and the flaky flag.
closes https://github.com/zama-ai/concrete-ml-internal/issues/3389
=> chore: remove flaky flag and skip test

script/doc_utils/check_forbidden_words.py
if we run the MNIST notebook locally, the forbidden words script makes `make pcc` fail (unless we remove the data). Let's just avoid checking these files are it's not really relevant here
=> chore: avoid advanced example data in forbidden words

.github/workflows/continuous-integration.yaml
Avoid triggering pytest in the CI when only changing Concrete ML's version (when preparing a release). Changing the version should not affect our tests and everything is tested in the release CI anyway
=> chore: avoid trigger pytest if only the Concrete ML version changes

src/concrete/ml/sklearn/base.py
This URL does not exist anymore (preventing us from building the documentation)
=> chore: remove wrong Concrete url from docstring

.github/workflows/continuous-integration.yaml
the docs/SUMMARY.md only has links but no codeblocks, but is changed when updating apidocs (which makes the prepare release CI trigger unnecessary codeblock tests)
=> chore: avoid triggering codeblock tests if SUMMARY.md changed

.github/workflows/release.yaml
This should fix 2 new issues : 
- some variables were not properly propagated through jobs: job outputs should be used instead of environment variables
- some jobs were using fresh containers instead of simply running on our host (and therefore avoid re-installing everything, hopefully)
There might be one more problem coming later (during the release packaging job, related to downloading artifacts built during the CI workflows) but it's still unclear on whether I really need to change something so I think it's better to first try and then see what happens
=> chore: fix release action (use job outputs and remove containers)

.github/workflows/release.yaml
Looks like there's a small issue in the action where an error is raised if the gpg-agent.conf file cannot be found (not sure what we stumble on it but I'll open an issue on their side). Meanwhile, manually creating the file should do the trick
=> chore: fix import-gpg step in release process

tests/sklearn/test_sklearn_models.py
Basically the flaky appeared because we were very unlucky : we were generating 2 datasets sequentially (with fixed seeds) using a new `random_state` each time. This `random_state` was generated through `random_state = numpy.random.randint(0, 2**15)`. Turns out, for seed `1687196373446039357`, two consecutive `randint` calls were outputting the same number (`26567`), which led `get_dataset` / `load_data` to generate the same dataset twice (and thus making the model's predictions identical in the test, while we expect a difference)
I therefore suggest to generate a random state manually once for generating the first dataset and then add 1 to it for generating the second dataset (so that we make sure both random states are different). I believe this should be enough but feel free to suggest …
=> fix: flaky test double_fit

.github/workflows/release.yaml
Based on my testings, it seems that the last error I got was related to the fact that the GPG keys were imported in a different job than the one that signs and pushes the tag, so hopefully that will work
=> chore: fix tag sign with gpg key in the release process

.github/workflows/release.yaml
Good news : signing tag now works
Bad news: push command was no right
=> chore: add origin when pushing tag in release process

.github/workflows/release.yaml
Two things here : 
- now the tag (and release branch) is pushed thanks to a github action (that should resolve access errors)
- enable the workflow to be triggered from a release branch (in order to handle patch releases, but that's still not quite supported yet)
=> chore: add push step to release process

.github/workflows/prepare_release.yaml, .github/workflows/release.yaml, script/make_utils/version_utils.py
Basically, the workflow for patch releases differs a bit as the dot release branch already exists. We'll need to : 
- prepare the release on main as usual. However, this time, the release process won't be automatically triggered (as opposed with major/minor releases or rc)
- manually create a branch from the release branch + cherry pick the necessary commits + open a PR targetting the release branch
- once the PR is merged, the release process is automatically triggered (we therefore accept the release workflow to be triggered from a a release branch, and we won't try to create a new one)
=> chore: handle patch releases

.github/workflows/release.yaml
Jobs are separated runners, we therefore need to install dependencies again in order to pursue even if we already did in the first job (without using cache or upload/download them as artifacts). Also, it's not possible to do everything in one step as the reusable CI workflow (our tests) needs to be a job by itself
=> chore: install dependencies in package release job

.github/workflows/prepare_release.yaml, .github/workflows/release.yaml
Basically : 
- for major/minor releases or release candidates : run prepare release from main (else it fails) and the release process will follow automatically (once the preparation pr is merged)
- for patch releases :  run prepare release from the right (ie, with matching version) release branch (else it fails) and the release process will follow automatically (once the preparation pr is merged)
=> chore: run prepare release from release branch for patches

.github/workflows/release.yaml
The issue is already fixed : https://github.com/crazy-max/ghaction-import-gpg/issues/176
Also had to put back the `sudo apt-mark hold docker.io` even though we don't need it in regular CIs (still unsure why but it blocked the release process' deps installation)
=> chore: remove GPG import workaround in release workflow

use_case_examples/cifar_brevitas_training/bnn_pynq_train.py, use_case_examples/cifar_brevitas_training/evaluate_one_example_fhe.py, use_case_examples/cifar_brevitas_training/evaluate_torch_cml.py, use_case_examples/cifar_brevitas_training/trainer.py
We observed a small (~1.5% with 6 bits rounding) drop in accuracy when using a better (more representative) compilation inputset, which is currently being investigated : https://github.com/zama-ai/concrete-ml-internal/issues/3957
In the mean time, this should solve the very low top1 accuracy we currently face (17% -> 86% top1 accuracy with 6 bits rounding)  
closes https://github.com/zama-ai/concrete-ml-internal/issues/3939
=> fix: fix bad top1 accuracy in cifar_brevitas_training use case

src/concrete/ml/sklearn/qnn_module.py, tests/sklearn/test_qnn.py
Structured pruning and unstructured pruning were causing some bad interference. 
Having both on the same layer caused pruning to be removed twice from that layer which causes a torch assert.
=> fix: make sure structured pruning and unstructured pruning work well together

.github/workflows/continuous-integration.yaml
Not a huge fan of triggering the CI if any changes has been found in the makefile as not all commands are impacting the CI, but since there are still a few of them I can't find a better solution than that (cc @bcm-at-zama )
closes https://github.com/zama-ai/concrete-ml-internal/issues/3955
=> chore: trigger CI if Makefile changes

.github/workflows/continuous-integration.yaml
By default, several steps would be skipped if the CI was triggered manually through GitHub's Action interface (ex: https://github.com/zama-ai/concrete-ml/actions/runs/6123285209/job/16620945850)
I fixed that by skipping the "check for changes" step, which should prevent other steps from being skipped
=> chore: run all CI steps if triggered manually

use_case_examples/cifar_brevitas_training/README.md, use_case_examples/cifar_brevitas_training/evaluate_torch_cml.py
It turns out there was not a bug, this is the new accuracy we should talk about. Basically, we were not properly calibrating before, but more details can be found in https://github.com/zama-ai/concrete-ml-internal/issues/3957 
closes https://github.com/zama-ai/concrete-ml-internal/issues/3957
=> docs: update cifar_brevitas_training accuracy using representative calibration set

tests/torch/test_compile_torch.py
Flag the test as flaky until it's fixed
refs https://github.com/zama-ai/concrete-ml-internal/issues/3989
=> chore: flag test_torch_padding as flaky

src/concrete/ml/sklearn/base.py, src/concrete/ml/sklearn/linear_model.py, src/concrete/ml/sklearn/qnn.py, src/concrete/ml/sklearn/rf.py, src/concrete/ml/sklearn/svm.py, src/concrete/ml/sklearn/tree.py, src/concrete/ml/sklearn/xgb.py, tests/sklearn/test_qnn.py
This should simplify our code base without breaking anything. Also, it's somewhat necessary for https://github.com/zama-ai/concrete-ml-internal/issues/3809. Since this includes some API breakings, I added property methods with a warning message saying that both attributes are now deprecated 
closes https://github.com/zama-ai/concrete-ml-internal/issues/3835
=> chore: remove custom classifier attributes

tests/torch/test_compile_torch.py
The issue was that we assumed that none of the values in the test input were mapped to 0 by the quantization.
This assumption was proved to be false.
A simple way to force that no value is set to 0 by the quantizer, learned over [0,1], is to simply set the test input to 1 everywhere.
=> fix: fix flaky padding test

script/make_utils/generate_authenticated_pip_urls.sh
we have seen that, sometimes, keyring was not available, for no obvious reason. I am not able to say when keyring is or is not installed, so let's be sure it's here, by running installation when it's needed (will not do anything if it's already installed) 
closes #https://github.com/zama-ai/concrete-ml-internal/issues/3950
=> chore: be sure to have keyring installed

docs/built-in-models/tree.md
small missing part in https://docs.zama.ai/concrete-ml/built-in-models/tree
=> chore: adding XGBRegressor in this sentence

.gitignore, src/concrete/ml/deployment/fhe_client_server.py, src/concrete/ml/onnx/convert.py, src/concrete/ml/sklearn/tree_to_numpy.py, src/concrete/ml/torch/compile.py, src/concrete/ml/torch/hybrid_model.py, src/concrete/ml/torch/numpy_module.py, tests/torch/test_compile_torch.py, tests/torch/test_hybrid_converter.py, use_case_examples/hybrid_model/README.md, use_case_examples/hybrid_model/compile_hybrid_llm.py, use_case_examples/hybrid_model/infer_hybrid_llm_generate.py, use_case_examples/hybrid_model/requirements.txt, use_case_examples/hybrid_model/serve.sh, use_case_examples/hybrid_model/serve_model.py, use_case_examples/llm/QGPT2Evaluate.ipynb
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3842 
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3869
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3875
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3855
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3852
=> chore: implement hybrid model demo with GPT-2

.github/workflows/update_licenses.yaml
This should avoid the creation of PRs in other PRs by just directly pushing to the branch (if not main or release branch), as done with refresh_one_notebook !
cc @fd0r
=> chore: make license action directly push to regular branches

src/concrete/ml/torch/hybrid_model.py, tests/torch/test_hybrid_converter.py, use_case_examples/hybrid_model/infer_hybrid_llm_generate.py
Add a method to `HybridModel` to set the `fhe_local_mode` of all `RemoteModule`s at once.
closes https://github.com/zama-ai/concrete-ml-internal/issues/4000
=> chore: add method to set fhe local mode of all remote modules

.github/workflows/continuous-integration.yaml
Without it, the "coverage" comment erases the previous "re-run flaky" comment (and vice-versa), which was not expected
=> chore: add header to distinguish coverage and flaky comments in PRs

.github/workflows/update_licenses.yaml
Without it, we are not able to tun the license action when using CP nightly versions
=> chore: enable license action to install CP nightly versions

.github/workflows/update_licenses.yaml
Without it, only one of the two license update can be merged directly into a non-main / non-release branch using the action (ex: https://github.com/zama-ai/concrete-ml/actions/runs/6309990940/job/17131033599)
=> chore: add pull to license action

src/concrete/ml/sklearn/base.py, tests/deployment/test_client_server.py, tests/sklearn/test_sklearn_models.py
Issue explained: https://github.com/zama-ai/concrete-ml-internal/issues/4014
In this PR:
- I changed some variable names, I found them confusing.
- Disabled the test_client_server and double_fit tests for concrete knn
- I took the opportunity to remove an ugly loop in base.py and replace it with slicing. I thought that slicing wasn't allowed in FHE.
refs #https://github.com/zama-ai/concrete-ml-internal/issues/4014
closes #https://github.com/zama-ai/concrete-ml-internal/issues/4009
closes #https://github.com/zama-ai/concrete-ml-internal/issues/4017
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4001
=> disable   test_client_server and double_fit tests for concrete knn

conftest.py, src/concrete/ml/common/serialization/decoder.py, src/concrete/ml/pytest/utils.py, src/concrete/ml/search_parameters/p_error_search.py, src/concrete/ml/sklearn/__init__.py, src/concrete/ml/sklearn/base.py, tests/common/test_pbs_error_probability_settings.py, tests/common/test_serialization.py, tests/common/test_skearn_model_lists.py, tests/deployment/test_client_server.py, tests/parameter_search/test_p_error_binary_search.py, tests/seeding/test_seeding.py, tests/sklearn/test_common.py, tests/sklearn/test_dump_onnx.py, tests/sklearn/test_pandas_errors.py, tests/sklearn/test_qnn.py, tests/sklearn/test_sklearn_models.py, tests/torch/test_brevitas_qat.py
Several things have been done here : 
- it's now possible to import fitted **linear** sklearn models in Concrete ML through the `.from_sklearn_model` method (name to be confirmed)
- test suite has been improved : 
- it's easier to filter in/out models for tests (only consider linear models, exclude "DecistionTree" models, only consider "XGBClassifier", ect), instead of having to put "if ... then: return" (which made pytest and debuggers still display irrelevant test configurations)
- `sklearn_models_and_datasets` has been replaced by `MODELS_AND_DATASETS` (more relevant)
- `UNIQUE_MODELS_AND_DATASETS` replaced `get_random_extract_of_sklearn_models_and_datasets` (the function's name was misleading, as nothing was random + it's now easier to use)
-  some tests run less configurations (by …
=> feat: enable import of fitted linear sklearn models

src/concrete/ml/deployment/fhe_client_server.py
This factorization makes the client.load method check for the python version as well 
closes https://github.com/zama-ai/concrete-ml-internal/issues/3993
=> chore: factor package checking code in fhe_client_server.py

.github/workflows/continuous-integration.yaml, Makefile, script/make_utils/pytest_pypi_cml.sh
Basically, this should run our tests (regular tests, no flaky) using Concrete ML's latest published version on PyPI just after being successfully released on GitHub
closes https://github.com/zama-ai/concrete-ml-internal/issues/2675
=> chore: add tests on latest CML pip version after release

Makefile
`linkchecker` does not seem to provide a way to add a simple delay or retry , so instead let's make it ignore arxiv.org links like we did for openml.org
closes https://github.com/zama-ai/concrete-ml-internal/issues/4023
=> chore: disable arxiv in linkchecker because of recurrent timeouts

.github/workflows/prepare_release.yaml
I must have changed this by error after our last release
=> chore: fix prepare_release action for non-patch releases

.github/workflows/prepare_release.yaml, .github/workflows/refresh-notebooks.yaml, .github/workflows/refresh-one-notebook.yaml, .github/workflows/release.yaml, .github/workflows/update_licenses.yaml
without this, these actions would basically wait for each others before being launch as they were put in the same concurrency group (which created some issues like having the `prepare_release` action wait for the `refresh_one_notebook` action before running) cc @fd0r
=> chore: add proper currency groups to GitHub actions

.github/workflows/refresh-notebooks.yaml, script/make_utils/jupyter.sh
closes https://github.com/zama-ai/concrete-ml-internal/issues/3764
=> chore: make refresh notebook still commit successful notebooks on fail

script/actions_utils/check_tag_not_remote.sh
checking that the tag did not exist was done using a grep on the tag name only, but the problem is that `grep "1.2.0"` and `grep "1.2.0-rc0"` both returns the same thing. We fix this by forcing the tag name to be the end of a line
=> chore: fix check tag step in release action

.github/workflows/release.yaml
So basically, I recently changed concurrency groups in workflows to make sure they have unique references using `group: "${{ github.ref }}-${{ github.event_name }}-${{ github.workflow }}"` . Turns out, it's not well supported when using reusable workflow.  
Basically, `github.workflow` are made the same between the called and caller workflows (source: https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow). This made the test CI workflow cancel the release workflow since they both share the same group ref but the CI one cancels all previous runs in progress when not triggered by a push on main (https://github.com/zama-ai/concrete-ml/blob/1516ee25024f618b01ee047efac332544cb25358/.github/workflows/continuous-integration. …
=> chore: fix concurrency group in release action

.github/workflows/release.yaml
For major/minor releases, we were creating the release branch locally but still trying to push to main (github.ref), which was a problem
=> chore: make the release action puth to the correct branch

.github/workflows/continuous-integration.yaml
without this, the "changed files" step would be run even for non-PR CIs
=> chore: fix condition evalution for steps in release action

tests/sklearn/test_sklearn_models.py
Fix some recent changes that made the weekly CI fail (https://github.com/zama-ai/concrete-ml/actions/runs/6450198846/job/17509408289)
=> chore: fix test_separated_inference in weekly CI

script/make_utils/pytest_pypi_cml.sh
We currently have some coverage issues with pypi tests in the weekly CI (https://github.com/zama-ai/concrete-ml/actions/runs/6450198846/job/17509408289). Not sure why it happens but let's start with updating the packages used 
Besides, we should probably take another look at https://github.com/zama-ai/concrete-ml-internal/issues/2005 and more specifically https://github.com/zama-ai/concrete-ml-internal/issues/2685 in order to avoid such manual updates
=> chore: update packages used in tests with pypi

README.md, use_case_examples/cifar/cifar_brevitas_training/README.md
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4047
=> chore: fix cifar runtime

Makefile
Skip the notebook in weekly CI tests until the AMi is fixed cc @fd0r 
refs https://github.com/zama-ai/concrete-ml-internal/issues/4064
=> chore: skip deployment notebook in pytest_nb

Makefile, script/make_utils/pytest_pypi_cml.sh
closes https://github.com/zama-ai/concrete-ml-internal/issues/4042
=> chore: rename CP_VERSION_SPEC_FOR_RC for coherence

.github/workflows/release.yaml
I think putting the tag list (https://hub.docker.com/r/zamafhe/concrete-ml/tags) instead of the direct image associated to the tag (https://hub.docker.com/layers/zamafhe/concrete-ml/v1.2.0/images/sha256-94fcd06c55d9f170aab594ba171e6d76ad90a6da110696528a3fb399d50e3a00) is better because less verbose and easier to add (otherwise we need to retrieve the docker image's sha256)
closes https://github.com/zama-ai/concrete-ml-internal/issues/4045
=> chore: add Docker Hub link in release changelogs

.github/workflows/continuous-integration.yaml
without this (which is reverting a small commit from last week), the CI remains green even if some tests or coverage fails (as we can see in https://github.com/zama-ai/concrete-ml/actions/runs/6496948965/job/17645139299?pr=333) 🙂  So better keep it that way
=> chore: revert cleaning of FAILED_TESTS_ARE_FLAKY in CI

.github/workflows/continuous-integration.yaml
Small bug that made the CI release fail when triggered automatically after merging the "prepare release" PR.
=> chore: fix triggering of release CI after prepapre_release

conftest.py, src/concrete/ml/common/utils.py, src/concrete/ml/quantization/quantized_module_passes.py, src/concrete/ml/quantization/quantizers.py, src/concrete/ml/sklearn/base.py, tests/onnx/test_onnx_ops_impl.py, tests/quantization/test_quantizers.py, tests/sklearn/test_sklearn_models.py, tests/torch/test_compile_torch.py
The problem occurred after I merged the changes of this PR (https://github.com/zama-ai/concrete-ml/pull/333) yesterday.
Where I added the `get_topk_labels` method to the `predict` of KNN class.
- The issue comes from the squeeze operation:
If the input shape is (1, 1, k), squeezed turns it to (k,). Which I have corrected it.
- Why the test didn't catch this problem?
`numpy.isclose`, compares elements in arrays but doesn't consider their shape.
Exemple:
```
a = numpy.array([0])
b = numpy.array([0, 0, 0])
numpy.isclose(a, b, rtol=0, atol=0.001)
True
```
In the flaky: https://github.com/zama-ai/concrete-ml-internal/issues/4092:
```
a = numpy.array([0])
b = numpy.array([0, 0, 1])
numpy.isclose(a, b, rtol=0, atol=0.001)
False.
```
In this PR, I corrected the shape mismatch.
I changed …
=> chore: fix shape

benchmarks/common.py, docs/built-in-models/linear.md, docs/developer-guide/api/README.md, docs/developer-guide/api/concrete.ml.common.utils.md, docs/developer-guide/api/concrete.ml.quantization.quantized_module.md, docs/developer-guide/api/concrete.ml.sklearn.base.md, docs/developer-guide/api/concrete.ml.sklearn.linear_model.md, docs/developer-guide/api/concrete.ml.sklearn.neighbors.md, src/concrete/ml/sklearn/__init__.py, src/concrete/ml/sklearn/base.py, src/concrete/ml/sklearn/linear_model.py, tests/common/test_skearn_model_lists.py, tests/sklearn/test_common.py, tests/sklearn/test_dump_onnx.py, tests/sklearn/test_sklearn_models.py
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4093
=> Add SGD regressor

src/concrete/ml/onnx/onnx_model_manipulations.py, src/concrete/ml/sklearn/tree_to_numpy.py
Three minors things : 
- fix `tree_to_numpy` when we apply ceil/floor op : only apply it for the bia_1 tensor (where it's supposed to be applied)
- remove initializers associated with nodes cut from the graph
- fix comments in `tree_to_numpy.py` : sklearn uses `LessOrEqual` instead of `Greater` 
refs https://github.com/zama-ai/concrete-ml-internal/issues/196
closes https://github.com/zama-ai/concrete-ml-internal/issues/4115
closes https://github.com/zama-ai/concrete-ml-internal/issues/4116
closes https://github.com/zama-ai/concrete-ml-internal/issues/4110
cc @jfrery
=> chore: only apply ceil/floor op in tree_to_numpy function when necessary

use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py
The instance was not used anywhere and was blocking the ability to run the script several times in a row
=> chore: remove FHEModelDev in cifar training FHE evaluation script

.github/workflows/refresh-one-notebook.yaml
Without this, refreshing several notebooks one after the other targeting a same branch forces the workflows to run one after the other
=> chore: enable refresh_one_notebook action to run in parallel

.gitleaksignore, src/concrete/ml/pytest/torch_models.py, src/concrete/ml/quantization/post_training.py, src/concrete/ml/quantization/quantized_ops.py, tests/torch/test_compile_torch.py
ref https://github.com/zama-ai/concrete-ml-internal/issues/4073
ref https://github.com/zama-ai/concrete-ml-internal/issues/4106
ref https://github.com/zama-ai/concrete-ml-internal/issues/4144
=> feat: allow QuantizedAdd produces_output_graph

src/concrete/ml/pytest/torch_models.py
Following your lest commit @kcelia
=> chore: explain why TorchSum with a PBS is not included in coverage

docs/deep-learning/onnx_support.md, src/concrete/ml/onnx/onnx_utils.py, src/concrete/ml/onnx/ops_impl.py, src/concrete/ml/pytest/torch_models.py, src/concrete/ml/quantization/quantized_ops.py, tests/quantization/test_quantized_ops.py, tests/torch/test_compile_torch.py
ref https://github.com/zama-ai/concrete-ml-internal/issues/4158
I had to implement Equal as well because the `torch.norm(...)` seems to create an Equal node. It's only there to compute constants so it does not appear in the final FHE graph.
=> feat: support Expand Equal ONNX op

Makefile
Until now we used gitleaks to check the whole history but it makes more sense to only check from the first commit to the current commit.
Otherwise it would break all PRs if someone pushed something that was detected as a leak.
This introduces some issues also when working with multiple remotes.
The commit changes the behavior to check from first commit to current commit.
=> chore: change the way we use gitleaks

.github/workflows/single_benchmark.yaml, conftest.py, script/doc_utils/check_forbidden_words.py, script/make_utils/check_installation_with_all_python.sh, script/make_utils/pytest_pypi_cml.sh, src/concrete/ml/onnx/onnx_impl_utils.py, src/concrete/ml/onnx/ops_impl.py, src/concrete/ml/quantization/quantized_module.py, src/concrete/ml/quantization/quantized_ops.py, src/concrete/ml/sklearn/base.py
There is still a method called "cpn_round" in our mixin quantized op but that would create a breaking change, so I added it in https://github.com/zama-ai/concrete-ml-internal/issues/3995 
Also, there are a few (3 I think) links to some concrete-numpy-internal issues left
closes https://github.com/zama-ai/concrete-ml-internal/issues/4074
closes https://github.com/zama-ai/concrete-ml-internal/issues/2250
=> chore: remove last mentions of Concrete-Numpy

src/concrete/ml/onnx/ops_impl.py
I believe these optimizations are old, now the compiler should handle them (based on this comment for ex : https://github.com/zama-ai/concrete-compiler-internal/issues/788#issuecomment-1326138981)
do you confirm @bcm-at-zama ? cc @andrei-stoian-zama 
EDIT: actually there was an issue for it in CML (https://github.com/zama-ai/concrete-ml-internal/issues/154) but the one associated to it in old CN (https://github.com/zama-ai/concrete-numpy-internal/issues/1400) has been closes without confirmation that such an optim is done on the compiler side ... maybe @rudy-6-4 @umut-sahin or @BourgerieQuentin can confirm ?
=> chore: remove old optimization in numpy_gemm

README.md, src/concrete/ml/torch/compile.py
The `n_bits` configuration for `compile_torch_model` did not explain that weights&activations can have different bitwidths. I added this explanation. 
closes https://github.com/zama-ai/concrete-ml-internal/issues/2365
=> docs: document n_bits for compile torch functions

use_case_examples/credit_card_approval_prediction/README.md, use_case_examples/image_filtering/README.md
Similarly to what we've done for the image filtering space
=> docs: add links to credit card approval space in use case examples

docs/deep-learning/onnx_support.md, src/concrete/ml/onnx/onnx_utils.py, src/concrete/ml/onnx/ops_impl.py, src/concrete/ml/quantization/quantized_ops.py, tests/quantization/test_quantized_ops.py
Implement the QuantizedUnfold Class for support of Unfold Operation
See [this issue](https://github.com/zama-ai/concrete-ml/issues/467)
=> feat: implement quantized unfold

Makefile
in https://github.com/zama-ai/concrete-ml/pull/449, coverage failed but the CI remained green : this is because a flaky test failed and was re-run, but re-runned tests were not considered for coverage warning
this PR should fix this thanks to the `--cov-append` option
=> chore: fix coverage warning when re-running failed tests in CI

.github/workflows/cifar_benchmark.yaml, README.md, benchmarks/convert_cifar.py, ci/slab.toml, use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py
Update cifar workflow to be able to run on hpc7a using slab and expose p-error as a parameter of the cifar benchmark workflow.
=> chore: expose p-error to cifar-16b benchmark and slab

src/concrete/ml/pytest/torch_models.py
We should make sure to test the torch operators that we claim supporting, but maybe there's a better place where to do so (or have a dedicated test ?), so feel free to share your opinion on it
=> chore: add BatchNorm operator in compile_torch tests

.github/workflows/continuous-integration.yaml, script/actions_utils/pytest_failed_test_report.py
This is more grammatically correct !
=> chore: rephrase flaky warning message for PRs

src/concrete/ml/onnx/ops_impl.py, src/concrete/ml/quantization/quantized_ops.py, tests/quantization/test_quantized_ops.py
`auto_pad` and `count_include_pad` parameters are described in [ONNX's documentation](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#AveragePool-11) and I believe : 
- that we cannot support `auto_pad` (ie, we force explicit padding)
- we force `count_include_pad` to be True (ie, we include padded values when calculating values for the edges)
tell me what you think about it. I also took the liberty to add checks on our input asserts, as we already do for the conv operator 
closes https://github.com/zama-ai/concrete-ml/issues/428
closes https://github.com/zama-ai/concrete-ml-internal/issues/4203
=> fix: add support to AvgPool's missing parameters

docs/built-in-models/neural-networks.md, docs/deep-learning/torch_support.md
A user pointed that that this list was not up to date. Turns out we indeed added/changed quite some things since we've updated this section.
closes https://github.com/zama-ai/concrete-ml-internal/issues/4268
=> docs: update operator list in torch support's documentation section

Makefile, script/actions_utils/pytest_failed_test_report.py
This PR fixes two small issues related to https://github.com/zama-ai/concrete-ml/actions/runs/7817775612/job/21326578294 : 
- when rerunning flaky tests, since we now append the coverage, we also need to make sure that it still fails under 100% coverage + avoids printing covered lines for all files
- in the specific case where pytest crashes (syntax error in a test file), make sure we do no falsely detect a flaky test and trigger the rerun step (this was triggered if pytest failed + no non-flaky tests was found, but we now also make sure we do have at least a flaky test)
=> chore: improve flaky rerun step in CI (pytest crash, appended coverage)

.github/workflows/prepare_release.yaml, .github/workflows/release.yaml
In the current release process the concurrency group for release actions is just the name of the github action.
That means that we can't do a patch release and a minor release at the same, which is an issue.
I  propose to solve this by adding the github.ref to the concurrency group.
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> fix: fix concurrency issue in release process

.github/workflows/release.yaml
Python install is broken in the release process.
Let's change it with setup-python action
=> fix: replace python release install with setup-python

.github/workflows/continuous-integration.yaml
When Yuxi only modified the readme, the docs + check links steps were skipped : https://github.com/zama-ai/concrete-ml/actions/runs/7873209097/job/21480124606
we should check links whenever root mardown files (+ LICENSE file) are changed as well
=> chore: include root md file when checking links in CI

README.md, script/make_utils/local_link_check.py
The link was always wrong (ex: https://github.com/zama-ai/concrete-ml/actions/runs/7887169029/job/21521900852), but it looks like in some systems like macos, pathlib's `exists()` function is not case sensitive 🙂
=> chore: fix link to license file in the readme

.github/workflows/release.yaml, Makefile
Skorch is not available in the step of the release that launches the import of skorch.
This makes the import fail without error.
=> fix: make skorch import fail without error

src/concrete/ml/quantization/quantized_module.py
Else, it gives a lot of messages with ` input of an Transpose operation` , `input of an Slice operation` ... !
feels more natural to use `a` instead of `an` here
=> chore: fix small grammar error in QAT error message

src/concrete/ml/torch/hybrid_model.py
Allow FHE local execution for hybrid model to be able to bench the execution time
=> chore: enable local FHE execution to benchmark hybrid models

docs/SUMMARY.md
The tags were removed by accident by editing directly on Gitbook
=> fix: reinstate apidoc generated tags

.github/workflows/sync_on_push.yaml
it's still failing : https://github.com/zama-ai/concrete-ml/actions/runs/8522402034/job/23342541783
the issue is that the external action does not provide any LFS options
also, it looks like we were cloning the repo twice, so I remove the external action and simplified to these steps
=> chore: fix sync repository action (bis)

tests/torch/test_brevitas_qat.py
refs https://github.com/zama-ai/concrete-ml-internal/issues/4356
=> chore: mark test_brevitas_power_of_two as flaky

tests/torch/test_compile_torch.py
Fixme was supposed to link to https://github.com/zama-ai/concrete-ml-internal/issues/4331
=> chore: fix wrong fixme link

script/make_utils/pytest_pypi_cml.sh
second step towards a green weekly CI
closes https://github.com/zama-ai/concrete-ml-internal/issues/4251
=> chore: avoid checking for coverage in weekly tests with pypi

conftest.py, src/concrete/ml/sklearn/base.py, src/concrete/ml/sklearn/linear_model.py, tests/sklearn/test_fhe_training.py, tests/sklearn/test_sklearn_models.py
first step towards a green weekly CI 
So there are a few things to note in this PR : 
- the weekly CI was failing because SGD classifier's `post_processing` method was not properly integrated : instead, everything was done in `predict_proba`, which interferes with the way we build and test our API (notably the `test_separated_inference`)
- I found a more general "issue" related to linear models' `predict` method: while trees / qnns usually do `predict_proba` + `argmax`, for linear models sklearn does `decision_function` + `argmax`. In theory this should not change anything as the `predict_proba` basically does a sigmoid/softmax or normalization, but in practice it made the argmax behave differently because of slight floating points errors (basically the same as in …
=> fix: SGDClassifier post-processing with multi-class and improve linear models' predict method

script/make_utils/fix_omp_issues_for_intel_mac.sh
Doing recompilation of our HF endpoints for python3.10 allowed me to see that this script was not working fine for 3.10. Still restricted to Intel Mac, I guess.
Tested on my machine for 3.8, 3.9 and 3.10
It will also be tested by the `check_licenses` on the weekly build
closes #https://github.com/zama-ai/concrete-ml-internal/issues/4386
=> chore: fixing OMP lib installation issues on intel mac for other python versions

src/concrete/ml/quantization/quantized_module.py, src/concrete/ml/sklearn/base.py, tests/quantization/test_quantized_module.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4393
=> chore: use cp vl when circuit is CRT based

README.md, docs/getting-started/pip_installing.md
=> chore: update doc on docker support for apple silicon

src/concrete/ml/common/utils.py, tests/torch/test_compile_torch.py
fixing expected test error message which uses .keys() (random order)
=> chore: fix test rounding_threshold_bits

tests/sklearn/test_fhe_training.py
avoid a flaky test found in https://github.com/zama-ai/concrete-ml/actions/runs/8797093660/job/24141329313
this test was added very recently in a refactor PR but it does not make much sense to do it, so let's disable it
=> chore: avoid checking accuracy when early stop in FHE training

tests/deployment/test_client_server.py
we most likely forgot to mark this test as flaky since we already have this issue opened : https://github.com/zama-ai/concrete-ml-internal/issues/4014
seems pretty rare, but jut got it here : https://github.com/zama-ai/concrete-ml/actions/runs/8816931744/job/24202240638?pr=645
=> chore: mark  as flaky

use_case_examples/llm/qgpt2_class.py
This commit fixes a bug in use_cases_examples/llm/qgpt2_class.py demo where `simulate` was not called properly.
It raised `TypeError: unsupported operand type(s) for /: 'method' and 'int'` because `<bound method Circuit.simulate>` was not called.
=> fix: update qgpt2_class.py to fix typo

src/concrete/ml/deployment/fhe_client_server.py, tests/torch/test_hybrid_converter.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4434
=> chore: remove versions.json at root of deployment folder

tests/torch/test_hybrid_converter.py
let's close the associated issue but keep in mind that these warnings started to happen because poetry was somehow installing a higher version that what is written in the lock file
closes https://github.com/zama-ai/concrete-ml-internal/issues/4437
=> chore: add filter for FutureWarning raised by huggingface-hub 0.23

src/concrete/ml/sklearn/linear_model.py, tests/sklearn/test_fhe_training.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4439
=> chore: improve binary classification check in encrypted training

tests/torch/test_hybrid_converter.py
looks like I've put the filter on the wrong test last week (which made the weekly failed : https://github.com/zama-ai/concrete-ml-internal/actions/runs/8961437917)
=> chore: fix FutureWarning test filtering

.github/workflows/cifar_benchmark.yaml, ci/slab.toml
With the version of Slab (and the runner associated), there is a breaking change on how a backend is handled.
This will be merged once the latest release of Slab is shipped to production.
=> chore(ci): update usage of slab-github-runner to last version

docs/advanced_examples/ClientServer.ipynb, docs/guides/client_server.md, src/concrete/ml/deployment/fhe_client_server.py, src/concrete/ml/torch/hybrid_model.py, tests/deployment/test_client_server.py, use_case_examples/deployment/breast_cancer/client.py, use_case_examples/deployment/cifar/client.py, use_case_examples/deployment/sentiment_analysis/client.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4430
=> docs: update documentation on client / server API

.github/workflows/weekly_tests.yaml
without this, weekly tests that are manually triggered are skipped because they can conflict with the reusable CI workflow (ex: https://github.com/zama-ai/concrete-ml/actions/runs/9209078483)
=> chore: rename concurrency group for weekly action

.github/workflows/continuous-integration.yaml, .github/workflows/weekly_tests.yaml
without the secrets, the usual CI workflow could not run
=> chore: fix weekly workflow

ci/aws_ami_build_component.yaml, script/make_utils/pytest_pypi_cml.sh
else, the weekly pypi wheel tests fail : https://github.com/zama-ai/concrete-ml/actions/runs/9220877214/job/25368925115
I believe this is happening we've recently put the transformer library as a dev dependency
=> chore: add transformers library in pypi wheel tests

.github/workflows/continuous-integration.yaml, .gitignore, script/actions_utils/pytest_failed_test_report.py
this is following work done in https://github.com/zama-ai/concrete-ml/pull/662, it should fix the flaky re-run step (https://github.com/zama-ai/concrete-ml/actions/runs/9226803784/job/25387474616)
=> chore: fix flaky re-run step in CI

.github/workflows/continuous-integration.yaml
following the work done in https://github.com/zama-ai/concrete-ml/pull/662, but the final slack report failed (https://github.com/zama-ai/concrete-ml/actions/runs/9254999792/job/25468196365)
the fix comes from github's documentation : https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
this part is not easy to debug as it requires some flaky tests to be triggered but I did some local scripts and it looks like it should work
=> chore: fix multiline slack report for weekly CI

.github/workflows/sync_on_push.yaml
the fix has been made in the git-sync fork : https://github.com/RomanBredehoft/git-sync/commit/90c0b4d50224381109327f0513a7e7a90a766b2f
the reason was that we were pushing lfs files using 
```
git lfs push destination "${SOURCE_BRANCH}:${DESTINATION_BRANCH}"
```
but normally LFS only handles a single destination refs (https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-push.adoc) like : 
```
git lfs push destination "${DESTINATION_BRANCH}"
```
but for some reasons, the error just recently showed up
closes https://github.com/zama-ai/concrete-ml-internal/issues/4445
=> chore: fix local refs issue sync repo action

Makefile, script/make_utils/check_installation_with_all_python.sh, script/make_utils/pytest_pypi_cml.sh
the weekly crashes because of the `pip install` was missing some `--extra-index-url` for Concrete Python when installing wheels (https://github.com/zama-ai/concrete-ml/actions/runs/9386053499/job/25845972848)
there's probably a way of enabling it for all pip commands in the project but I couldn't find a proper and easy solution, so let's do that for now
=> chore: fix wheel install in weekly CI

script/make_utils/pytest_pypi_cml.sh
the weekly CI failed because of this (https://github.com/zama-ai/concrete-ml/actions/runs/9439787070/job/25998396955)
we should do https://github.com/zama-ai/concrete-ml-internal/issues/2685 at one point, it'll avoid such issues
=> chore: add pytest-subtests for pypi checks in weekly CI

.github/workflows/continuous-integration.yaml
The last weekly CI failed for an unknown reason (internal error from GitHub), letting some EC2 instances running (which required to be manually terminated): https://github.com/zama-ai/concrete-ml/actions/runs/9468836256
this PR adds a slack alerts that will better warn us about such an issue  cc @fd0r
=> chore: add slack alert when stopping EC2 instances fails in CI

src/concrete/ml/deployment/fhe_client_server.py, src/concrete/ml/quantization/quantized_module.py, src/concrete/ml/sklearn/base.py, src/concrete/ml/sklearn/linear_model.py, tests/deployment/test_client_server.py, tests/sklearn/test_fhe_training.py
we are compiling the fhe training circuit for fhe execution but only do simulation, which should speed up the test by a x2 factor. Usually compilation is quick, but in the composition case it can take around tens of seconds so this can save several minutes of running
for that, I need to remove the fixed values we've put in our compile method, which are not breaking changes since these are Concrete's default values + should allow anyone to be able to only compile for simulation or fhe execution (as explained abvoe)
=> chore: clean and speed up fhe training tests

docs/deep-learning/fhe_assistant.md, docs/deep-learning/torch_support.md, src/concrete/ml/onnx/ops_impl.py
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4497
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4387
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4487
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4498
=> Explain torch compile error messages, improve PTQ vs QAT doc

.github/workflows/release.yaml
Pypi doesn't accept external dependencies so we need to change the target of our release candidates this they will use Concrete Python's versions that are not hosted on pypi anymore.
=> chore: change target of release candidates to private index

pyproject.toml
this warning made the release CI for python 3.9 and 3.10 fail : 
- https://github.com/zama-ai/concrete-ml/actions/runs/9599832121/job/26475425698
- https://github.com/zama-ai/concrete-ml/actions/runs/9599832121/job/26475426012
=> chore: filter jax DeprecationWarning

tests/pandas/test_pandas.py
found in the recent rc action : https://github.com/zama-ai/concrete-ml/actions/runs/9601275300/job/26504800783
=> chore: fix pandas schema flaky test

.github/workflows/release.yaml
softprops/action-gh-release was unreliable with SLSA files. We are moving to github CLI to create a release.
=> chore: move away from softprops/action-gh-release

.github/workflows/release.yaml
downloading artifact with pattern create a subdir, so I went with a dedicated approach for slsa provenance files cc @fd0r
=> chore: handle slsa artifacts separately

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, .github/workflows/weekly_tests.yaml
The weekly tests should only be run once (on the public repository)
=> chore: disable weekly tests on the internal repository

src/concrete/ml/torch/hybrid_model.py
We currently have an import to `transformers` in the hybrid model source code but we don't have the library as a requirement, only a development dependency.
Importing the library dynamically should fix this.
=> fix: dynamic import of `transformers` in hybrid model

.github/workflows/continuous-integration.yaml
At the moment if provenance is skipped the build-status step is also skipped because it was in the needs parameter.
This blocked the PRs so should be removed.
=> chore: remove provenance need in build status

use_case_examples/hybrid_model/README.md
layer names have been updated on HF
=> chore: fix readme module names example for phi-1.5

src/concrete/ml/quantization/quantizers.py
The commit fixes a dtype check that we have in the `dequant` method of our quantizer.
Dtype objects are weird.
https://stackoverflow.com/questions/26921836/correct-way-to-test-for-numpy-dtype
=> fix: fix dtype check in quantizer dequant

Makefile, src/concrete/ml/pytest/torch_models.py, src/concrete/ml/quantization/base_quantized_op.py, src/concrete/ml/quantization/quantized_ops.py, tests/quantization/test_quantized_ops.py, tests/torch/test_compile_torch.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4418
closes https://github.com/zama-ai/concrete-ml-internal/issues/4163
ref https://github.com/zama-ai/concrete-internal/issues/716
=> feat: support encrypted mul div

script/make_utils/pytest_pypi_cml.sh
following work done in https://github.com/zama-ai/concrete-ml/pull/773#event-13684554108 from @fd0r , we can remove this little extra deps as they are included in `[dev]`
=> chore: clean pytest_pypi_cml

tests/quantization/test_quantized_ops.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4563
=> chore: mark test_all_arith_ops as flaky

README.md, docs/README.md, docs/built-in-models/linear.md, docs/deep-learning/torch_support.md, docs/getting-started/pip_installing.md, docs/tutorials/showcase.md
Added the developer survey banner in the most viewed docs and README page to promote the survey and gather feedback.
=> Add developer survey in doc

script/make_utils/pytest_pypi_cml.sh
not sure why this issue (https://github.com/zama-ai/concrete-ml/actions/runs/10343073361/job/28626854301) didn't happen last time I tried locally, now it should really fix the weekly ci
=> chore: fix wheel steps in weekly tests

.github/workflows/continuous-integration.yaml, README.md, deps_licenses/licenses_linux_user.txt.md5, deps_licenses/licenses_mac_intel_user.txt.md5, deps_licenses/licenses_mac_silicon_user.txt.md5, docs/getting-started/pip_installing.md, poetry.lock, pyproject.toml, script/actions_utils/generate_test_matrix.py, script/make_utils/check_installation_with_all_python.sh, script/make_utils/licenses.sh
- Adding support for python 3.11 in the CML sources/dep
- Adding tests with 3.11 in the weekly (on top of 3.8, 3.9, 3.10)
You may want, in a further PR, to change the default 3.8 python to a more recent 3.11 python for your tests. Maybe it would make the CI faster? You might also want to drop 3.8 support now, or wait EOL in October.
closes #https://github.com/zama-ai/concrete-ml-internal/issues/3774
=> feat: adding support for python3.11

src/concrete/ml/deployment/fhe_client_server.py
https://github.com/jdmarsh
> I have a client/server setup where we use the via_mlir flag to save/load the circuit. When the server.zip is generated with a different python version to what the server is running, this python version restriction prevents us from continuing. As long as the concrete/concrete-ml versions are identical, I don't see why the python version should restrict us from loading the MLIR in server side (Or why it should apply as a restriction even when not using via_mlir?). I've made a change to relax the python version restriction server side for MLIR cases.
> 
> | Please let me know if there is a good reason for this restriction to apply when sending an MLIR server.zip generated with a different python version. In that case I will find another way forward.
Closes …
=> Relax python version restrictions

tests/sklearn/test_sklearn_models.py
This bug was reported by the [Concrete team](https://zama-ai.slack.com/archives/C044G400J6N/p1726212715764299), who encountered an issue with the value of the environment variable “TREE_USE_ROUNDING” during their tests.
The TREE_USE_ROUNDING variable is set to “1” by default in our source code, which means that tree-based models are always used with the rounding feature enabled.
However, in our Pytest tests (tests/sklearn/test_sklearn_models.py), particularly in the tests “test_load_fitted_sklearn_tree_models” and “check_rounding_consistency”, we temporarily change the value of this variable to test the rounding consistency feature.
So, the 2 tests mentioned above can conflict if they are executed in parallel, as both modify the TREE_USE_ROUNDING variable. To isolate the changes and …
=> add monkeypatch context to test_load_fitted_sklearn_tree_models

script/make_utils/fix_omp_issues_for_intel_mac.sh
- Looks like the OMP issues also happen on ARM
- And by the way, we didn't have the fix for Python3.11
=> chore: fixing OMP issues for macOS ARM and Python3.11.

use_case_examples/deployment/server/README.md
Had a look to https://github.com/zama-ai/concrete-ml/tree/main/use_case_examples/deployment/server and I think there is a typo.
By the way: maybe we are missing a README in https://github.com/zama-ai/concrete-ml/tree/main/use_case_examples/deployment/? Should we move https://github.com/zama-ai/concrete-ml/tree/main/use_case_examples/deployment/server/README there? Or have another one?
It's because people say they have difficulties in deploying, see https://discord.com/channels/901152454077452399/901152454622740593/1285222791104303134 and further messages.
=> chore: fixing a typo

docs/advanced_examples/LogisticRegressionTraining.ipynb
The notebook had no obvious "FHE training" aspect in its name or in its title (Logistic Regression Training). I think it's a bit misleading for the quick readers, isn't it? Changing the name of the file is bad, it may break links, but what about changing its title to something like "Logistic Regression Training Over Encrypted Dataset"?
=> chore: renaming the notebook for more clarity

.github/workflows/continuous-integration.yaml
There is a step in the weekly / release CI that performs `pip install concrete-ml` which actually installs the public latest pypi version of CML. When adding a new supported python version, this step fails. In any case I dont' see the point of testing the previous CML public version in this manner.
=> fix: pip installation failing on new python version

.github/workflows/continuous-integration.yaml
We require PRs to push to main. The signature checker only works on PRs -> it should run only on PRs.
=> fix: only check signature on PRs

use_case_examples/deployment/README.md, use_case_examples/deployment/cifar/models/__init__.py, use_case_examples/deployment/cifar/models/cnv_2w2a.ini, use_case_examples/deployment/cifar/models/common.py, use_case_examples/deployment/cifar/models/model.py, use_case_examples/deployment/cifar/models/tensor_norm.py, use_case_examples/deployment/cifar/requirements.txt, use_case_examples/deployment/server/README.md
closes https://github.com/zama-ai/concrete-ml-internal/issues/4600
ref #873 
cc @bcm-at-zama
=> chore: add readme in root folder of deployment use case + fix cifar

Makefile, docs/guides/hybrid-models.md, script/make_utils/check_links_with_agent.py, src/concrete/ml/onnx/onnx_impl_utils.py, src/concrete/ml/pytest/torch_models.py, tests/quantization/test_quantized_ops.py, tests/torch/test_compile_torch.py
In this PR:
- I removed the issues 4563 and 4579, spotted by the [bot](https://github.com/zama-ai/concrete-ml-internal/actions/runs/11661108643 ) and also discussed in [slack](https://zama-ai.slack.com/archives/C02RX6CF3FV/p1730711800658109)
- I refactored `tests/torch/test_compile_torch.py::test_qat_import_check` test to improve clarity and isolate Tracer._is_tracing
- I moved AllZeroCNN to  the torch_models file
- ~Skip Temporarily: CNNOther (see [issue](https://github.com/zama-ai/concrete-ml-internal/issues/4667))~
closes https://github.com/zama-ai/concrete-ml-internal/issues/4667
=> Improve link-checker and fix Tracer issue

.github/workflows/continuous-integration.yaml
closes https://github.com/zama-ai/concrete-ml-internal/issues/4669
same vcpu machine but more available. ~Also use hpc7a for release~ Actually we need to switch region to get the hpc7a
=> chore: update weekly and release machines

.gitleaksignore, docs/advanced_examples/LoraMLP.ipynb, src/concrete/ml/torch/hybrid_model.py, tests/torch/test_hybrid_converter.py, use_case_examples/deployment/README.md
closes https://github.com/zama-ai/concrete-ml-internal/issues/4671
=> chore: fix hybrid model glwe lora mlp

.github/workflows/refresh-one-notebook.yaml
- `use_case_examples/titanic/download_data.sh` no longer exists.
- `SentimentClassification.ipynb` notebook is in `sentiment_analysis_with_transformer` folder and there is no download_data.sh file.
closes:
- https://github.com/zama-ai/concrete-ml-internal/issues/4692
- https://github.com/zama-ai/concrete-ml-internal/issues/4691
=> chore: remove usefless steps in `refresh-one-notebook.yaml` workflow.

src/concrete/ml/torch/hybrid_model.py
In this way we can use the GLWE backend in `generate` right after compilation
=> fix: set executor during compile

.github/workflows/continuous-integration.yaml, Makefile, ci/slab.toml, conftest.py, src/concrete/ml/torch/compile.py, src/concrete/ml/torch/hybrid_model.py, tests/common/test_utils.py, tests/deployment/test_client_server.py, tests/sklearn/test_sklearn_models.py, tests/torch/test_compile_torch.py, tests/torch/test_hybrid_converter.py, tests/torch/test_training.py
Steps:
- Add new machine [g4dn.2xlarge](https://aws.amazon.com/ec2/instance-types/g4/) to `ci/slab.toml` under `[backend.aws.gpu_ciprofile]` tag, to pick up the SHA see: https://github.com/zama-ai/slab-github-runner
- Add the gpu marker, in conftest.py
- Target the tests to run with gpu
- Add gpu setup in .github/workflows/continuous-integration.yaml
Current issues: 
The `start-runner-gpu-linux`  step runs on `ubuntu-24.04` and starts the GPU instance, `invidia-smi` won't work inside it.
The AMI size is defined at build time (see: `/dev/root` using `df -h`). Increasing the instance type won't affect disk space — we must expand the AMI storage and create a new snapshot:
Reminder:
A snapshot is an incremental backup of an EBS volume (the "hard drive" of an EC2 instance), capturing its exact …
=> GPU tests in CI

.github/workflows/continuous-integration.yaml, .github/workflows/gpu-tests.yaml, .github/workflows/weekly_tests.yaml, Makefile, ci/slab.toml, tests/deployment/test_client_server.py
- Add cooncrete-version flag
- Skip gpu tests if no files have been modified
- Add python versions dynamically 
issues:
1. Sometimes, I noticed that some tests get stuck, eg:
https://github.com/zama-ai/concrete-ml/actions/runs/14934527657/job/42010084796?pr=1087
https://github.com/zama-ai/concrete-ml/actions/runs/14934527657/job/41958886066?pr=1087
https://github.com/zama-ai/concrete-ml/actions/runs/15056166599/job/42326187623?pr=1087
https://github.com/zama-ai/concrete-ml/actions/runs/15056166599/job/42326187623?pr=1087
https://github.com/zama-ai/concrete-ml/actions/runs/15110189801/job/42467986563?pr=1087
I changed the gpu instance,~and it fixed it.~
I disabled the test: test_client_server_sklearn_inference
2. I got: 
```
file: .github/workflows/weekly_tests.yaml#L19
The workflow is not …
```
=> uplift gpu ci
