zama-ai/concrete-ml

- .github/ISSUE_TEMPLATE/release.md
- .github/workflows/check_github_issues.yaml
- .github/workflows/continuous-integration.yaml
- Makefile
- ci/aws_ami_build_component.yaml
- script/actions_utils/monitor.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3878
> chore: remove useless or broken mentions of concrete-ml-internal

- Makefile
refs https://github.com/zama-ai/concrete-ml-internal/issues/3882
> chore: remove make public_release

- Makefile
- conftest.py
- tests/parameter_search/test_p_error_binary_search.py
- tests/sklearn/test_sklearn_models.py
- tests/torch/test_compile_torch.py
- tests/torch/test_hybrid_converter.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3891
cc @bcm-at-zama @youben11
> chore: add pytest_no_flaky command and flag flaky tests

- tests/parameter_search/test_p_error_binary_search.py
following this comment https://github.com/zama-ai/concrete-ml/pull/129#discussion_r1284125616 cc @fd0r
> chore: add comment on marking module as flaky with pytest

- use_case_examples/llm/QGPT2Evaluate.ipynb
closes https://github.com/zama-ai/concrete-ml-internal/issues/3890
> docs: rectify n_bits in text from llm use case notebook

- .github/workflows/prepare_release.yaml
- .github/workflows/release.yaml
add some forgotten steps
refs https://github.com/zama-ai/concrete-ml-internal/issues/3924
> chore: fix release actions

- .github/workflows/prepare_release.yaml
- .github/workflows/release.yaml
it's not necessary for this step and removing it avoids creating unnecessary problems
refs https://github.com/zama-ai/concrete-ml-internal/issues/3924
> chore: remove docker setup from prepare release action

- Makefile
> chore: remove set_version_no_commit command

- .github/workflows/continuous-integration.yaml
- .github/workflows/prepare_release.yaml
- .github/workflows/release.yaml
refs https://github.com/zama-ai/concrete-ml-internal/issues/3924
> chore: fix release action

- tests/torch/test_brevitas_qat.py
refs https://github.com/zama-ai/concrete-ml-internal/issues/3933
> chore: add flaky mark to test_brevitas_tinymnist_cnn

- script/make_utils/check_issues.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3942
> chore: fix check_github_issues action

- .github/workflows/prepare_release.yaml
- .github/workflows/release.yaml
Forgot to fix a syntax error last time, I tested the script locally and it should now work properly. I also made the error messages a bit more clear
> chore: fix syntax error in release workflow

- .gitignore
- use_case_examples/cifar_brevitas_training/evaluate_one_example_fhe.py
- use_case_examples/cifar_brevitas_training/evaluate_torch_cml.py
- use_case_examples/cifar_brevitas_training/trainer.py
The use case directory needed a bit of update (easier to read and debug now). Also , the `accuracy` function can now properly compute several top_k measures
> chore: clean and fix cifar training use case

- use_case_examples/cifar_brevitas_finetuning/cifar_utils.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3958
> chore: fix cifar pre-processing

- script/make_utils/fix_omp_issues_for_intel_mac.sh
the script was failing on mac silicon
> chore: avoid mac silicon in OMP script

- src/concrete/ml/pytest/torch_models.py
- src/concrete/ml/torch/compile.py
- src/concrete/ml/torch/hybrid_model.py
- tests/torch/test_hybrid_converter.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3992
> feat: support qat models in hybrid model

- src/concrete/ml/torch/hybrid_model.py
- tests/torch/test_hybrid_converter.py
- use_case_examples/hybrid_model/serve_model.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3998
> chore: implement HybridFHEModelServer to server hybrid models

- docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb
- docs/advanced_examples/GLMComparison.ipynb
- docs/advanced_examples/PoissonRegression.ipynb
- docs/advanced_examples/XGBRegressor.ipynb
- use_case_examples/federated_learning/federated_utils.py
- use_case_examples/federated_learning/load_to_cml.py
> chore: fix typo

- use_case_examples/federated_learning/fix_grpc.sh
- use_case_examples/federated_learning/requirements.txt
In order to solve the following vulnerability issue : https://github.com/zama-ai/concrete-ml/security/dependabot/126
> chore: update numpy version in FL use case

- .github/workflows/continuous-integration.yaml
following your last comment @fd0r
> chore: clean FAILED_TESTS_ARE_FLAKY variable in CI

- .github/workflows/check_github_issues.yaml
- .github/workflows/ci_timing.yaml
- script/make_utils/check_issues.py
The action was failing for some dependency installation problems : https://github.com/zama-ai/concrete-ml/actions/workflows/check_github_issues.yaml
Also, let's make it weekly instead of daily (Monday mornings) !
EDIT: Works great now : https://github.com/zama-ai/concrete-ml/actions/runs/6483203426/job/17604258183
> chore: fix check github issues

- docs/developer-guide/api/README.md
- docs/developer-guide/api/concrete.ml.sklearn.base.md
- docs/developer-guide/api/concrete.ml.sklearn.neighbors.md
- docs/developer-guide/api/concrete.ml.sklearn.tree_to_numpy.md
- docs/developer-guide/api/concrete.ml.sklearn.xgb.md
- docs/developer-guide/api/concrete.ml.torch.hybrid_model.md
- src/concrete/ml/sklearn/neighbors.py
- src/concrete/ml/torch/hybrid_model.py
Issues reported here: https://github.com/zama-ai/concrete-ml/pull/344
> chore: fix some doc issues

- src/concrete/ml/sklearn/linear_model.py
- src/concrete/ml/sklearn/neighbors.py
Small cleaning I stumbled upon while going through the project
> chore: small cleaning serialization

- use_case_examples/cifar/cifar_brevitas_finetuning/CifarInFhe.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/CifarInFheWithSmallerAccumulators.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/CifarQuantizationAwareTraining.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/FromImageNetToCifar.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/PerrorImpactOnFMNIST.ipynb
- use_case_examples/hybrid_model/infer_hybrid_llm_generate.py
refs https://github.com/zama-ai/concrete-ml-internal/issues/3953
> chore: remove use of MPS device

- use_case_examples/cifar/cifar_brevitas_training/README.md
Small typo as pointed out by @bhuvneshchaturvedi2512 in https://github.com/zama-ai/concrete-ml/issues/380
> chore: correct FHE evaluation command in cifar training readme

- docs/advanced_examples/XGBClassifier.ipynb
These prints are not MCC scores anymore
> chore: correct accuracy display in XGBclassifier notebook

- src/concrete/ml/pytest/torch_models.py
- src/concrete/ml/quantization/base_quantized_op.py
- src/concrete/ml/quantization/post_training.py
- src/concrete/ml/quantization/quantized_module_passes.py
- src/concrete/ml/quantization/quantized_ops.py
- tests/quantization/test_quantized_ops.py
- tests/sklearn/test_qnn.py
- tests/torch/test_brevitas_qat.py
- tests/torch/test_compile_torch.py
- tests/torch/test_training.py
- handling gemm over 2 encrypted inputs (we now have our own matmul trick)
- support multiple rounding operation in one quantized op
- handle 3 dimensional input in gemm (required for training)
- quantized gemm test
- test compile and fhe simulation run based on a torch model
> feat: encrypted gemm support - 3d inputs - better rounding control

- .github/workflows/ci_timing.yaml
> chore: fix CI timing's workflow

- src/concrete/ml/pytest/torch_models.py
- src/concrete/ml/quantization/quantized_ops.py
- tests/quantization/test_quantized_ops.py
- tests/torch/test_reduce_sum.py
ReduceSum's implementation was assuming that the input considered for the torch model did not have a batch dimension. However, in Concrete ML, we always need to have a batch dimension, as the inference in Concrete Python has to be done over single-batched inputs. Let's first make this clear in the documentation overall, and then see if it could be possible to also manage inputs with no batch dimension
cc @fd0r @jfrery 
refs https://github.com/zama-ai/concrete-ml-internal/issues/4180
closes https://github.com/zama-ai/concrete-ml-internal/issues/4094
> fix: fix wrong assumption in ReduceSum operator's axis parameter

- tests/sklearn/test_sklearn_models.py
if pytest is green, let's clean that
closes https://github.com/zama-ai/concrete-ml-internal/issues/4088
> chore: removing these per-model threshold, they are no more needed

- docs/advanced_examples/QuantizationAwareTraining.ipynb
refs https://github.com/zama-ai/concrete-ml-internal/issues/3953
> chore: remove last MPS occurence

- Makefile
To make sure everyone has the right poetry version ! cc @jfrery
> chore: fix poetry version check in sync_env make target

- README.md
closes https://github.com/zama-ai/concrete-ml-internal/issues/4231
> chore: add a contribution section in the readme

- src/concrete/ml/sklearn/_fhe_training_utils.py
https://github.com/zama-ai/concrete-ml-internal/issues/4144 was closed manually but a FIXME was still targeting it
> chore: remove FIXME targetting closed issue

- pyproject.toml
- src/concrete/ml/onnx/convert.py
- src/concrete/ml/onnx/ops_impl.py
- src/concrete/ml/quantization/quantized_module.py
- tests/quantization/test_quantized_module.py
- tests/torch/test_compile_torch.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4242
> chore: refacto quantized module init + handle no input onnx

- docs/developer-guide/contributing.md
Some things were unclear or out-of-date cc @andrei-stoian-zama
> docs: improve contributing section

- .github/workflows/prepare_release.yaml
- .github/workflows/update_licenses.yaml
- .github/workflows/weekly-pip-audit.yaml
- Makefile
- script/make_utils/setup_os_deps.sh
This fixes the weird syntax error we got when updating poetry to 1.3 and above on my side for some obscure reasons. Hopefully it'll work for the CI as well 🤞 
closes https://github.com/zama-ai/concrete-ml-internal/issues/4217
> chore: upgrade poetry to 1.7.1 and fix associated syntax error

- .github/workflows/cifar_benchmark.yaml
This helps to launch the bench using an alternative wheel from concrete CI and alternative concrete python branch
> chore: custom cp for cifar bench

- README.md
- script/doc_utils/check_forbidden_words.py
Reorganized existing content to follow the new structure
Aligned all the header links and badges
Added a table of contents
Added a call-to-action for users to star the repo
Checked all links and replaced outdated ones.
Unified the formatting
Updated the support banner
Improved the overall content quality
Added missing content where necessary
Added more “resources” for each product
Ensured wording is consistent throughout
> docs: update Readme.md

- script/make_utils/check_installation_with_all_python.sh
I believe this should fix the error we encountered in https://github.com/zama-ai/concrete-ml/actions/runs/7898959871/job/21557817557 cc @fd0r 
refs https://github.com/python-poetry/poetry/issues/2756#issuecomment-667105658
> chore: fix installation test with clone step

- use_case_examples/cifar/cifar_brevitas_with_model_splitting/README.md
issue https://github.com/zama-ai/concrete-ml-internal/issues/2383 has been closes manually and made https://github.com/zama-ai/concrete-ml/actions/runs/8138319644/job/22238844854 fail
> chore: remove link to issue 2383

- .github/workflows/continuous-integration.yaml
- .github/workflows/sync_on_push.yaml
seems to fail because of LFS (linked to the files added in the dataframe PR) : https://github.com/zama-ai/concrete-ml/actions/runs/8519619575/job/23334037322
> chore: fix sync action

- conftest.py
- src/concrete/ml/common/utils.py
- src/concrete/ml/quantization/post_training.py
- src/concrete/ml/torch/compile.py
- tests/torch/test_compile_torch.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4351
> chore: refacto compile to handle rounding_threshold_bits

- use_case_examples/cifar/cifar_brevitas_training/README.md
- use_case_examples/cifar/cifar_brevitas_training/evaluate_torch_cml.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4352
> chore: update cifar training readme + accuracy eval

- docs/SUMMARY.md
- docs/developer/support_new_onnx_node.md
- docs/index.toc.txt
closes https://github.com/zama-ai/concrete-ml-internal/issues/4358
> chore: add documentation to support new onnx node

- docs/README.md
- docs/developer/project_setup.md
Minor doc change requested by @yuxizama 
Can you @zama-ai/machine-learning also have it applied in the 1.5 branch please
> fix: minor doc change

- Makefile
- script/make_utils/check_first_line_is_different_from_other_lines.py
- script/make_utils/check_pytest_determinism.sh
- tests/seeding/test_seeding_system_file_a.py
- tests/seeding/test_seeding_system_file_b.py
by checking that the seed depends on the file name, function name and parameter 
so:
- it was already working, we had already a seed which was different from one file/function/param to the other
- but I've added tests to prove / check it
Principle of the test:
- we have a few functions in two different files doing the same exact call to random picking
- we run them and put everything in a text file
- then, we check that the first line of this text file is different from others, to check that:
(i) generated numbers are different
(ii) sub_seed is different
which proves that, even if you copy a test in different files and functions and parameters, their PRNG is going to behave differently, thanks to the sub_seed system which is different per us
closes …
> chore: add another test that our seeding system is good

- src/concrete/ml/pytest/torch_models.py
- tests/torch/test_reduce_sum.py
New steps towards a green CI 
We are removing the tlu in this test as sum should sort of always be followed with rounding before a tlu
> chore: remove TLU in reduce_sum test

- .github/workflows/continuous-integration.yaml
- docs/advanced_examples/DecisionTreeRegressor.ipynb
New steps towards a green weekly CI
> chore: fix broken notebooks from weekly

- use_case_examples/llm/requirements.txt
This should remove this vulnerability : https://github.com/zama-ai/concrete-ml/security/dependabot/185
> chore: update package  in LLM use case

- pyproject.toml
refs https://github.com/zama-ai/concrete-ml-internal/issues/4395
> chore: add fixme to update ONNX package

- src/concrete/ml/sklearn/linear_model.py
- tests/sklearn/test_fhe_training.py
I was starting to work on https://github.com/zama-ai/concrete-ml-internal/issues/4374 but realized the SGDClassifier could benefit from a bit of cleaning
also wanted to fix https://github.com/zama-ai/concrete-ml-internal/issues/4184 but it's actually not that trivial so we'll see later if it's really needed
> chore: clean encrypted training and SGDClassifier files

- script/make_utils/run_use_case_examples.sh
closes https://github.com/zama-ai/concrete-ml-internal/issues/4401
> chore: improve reliability of project root path in run_use_case_examples script

- docs/advanced_examples/FullyConnectedNeuralNetworkOnMNIST.ipynb
- script/make_utils/local_link_check.py
- use_case_examples/cifar/cifar_brevitas_finetuning/CifarInFhe.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/CifarQuantizationAwareTraining.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/FromImageNetToCifar.ipynb
- use_case_examples/cifar/cifar_brevitas_finetuning/PerrorImpactOnFMNIST.ipynb
- use_case_examples/titanic/KaggleTitanic.ipynb
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4372
> chore: check links in notebooks and fix issues

- Makefile
- script/make_utils/update_encrypted_dataframe_files.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4404
cc @andrei-stoian-zama
> chore: add make target for updating encrypted dataframe files

- src/concrete/ml/sklearn/rf.py
- src/concrete/ml/sklearn/xgb.py
- tests/sklearn/test_sklearn_models.py
Useful to keep consistency with sklearn / xgboost
> chore: add check initialization variables cml models vs sklearn

- tests/sklearn/test_fhe_training.py
Just to make sure predict works as well
> chore: improve test for single class in FHE training

- src/concrete/ml/sklearn/linear_model.py
- tests/sklearn/test_fhe_training.py
We had an issue with the way we supported classes, and more specifically in the `partial_fit` method.
We now have the same behavior as scikit-learn.
> fix: fix fhe-training classes behavior

- docs/advanced_examples/ConvolutionalNeuralNetwork.ipynb
closes https://github.com/zama-ai/concrete-ml-internal/issues/4443
cc @bcm-at-zama
> chore: remove mention of QAT in conv notebook

- .github/workflows/continuous-integration.yaml
- script/actions_utils/pytest_failed_test_report.py
small improvement, for better readability
> chore: improve slack report format for weekly CI

- script/make_utils/pytest_pypi_cml.sh
else, the weekly CI is red : https://github.com/zama-ai/concrete-ml/actions/runs/9341505322/job/25708428364
> chore: add pypi extra url for pytest check with pypi

- .github/workflows/refresh-one-notebook.yaml
- src/concrete/ml/quantization/quantized_ops.py
- use_case_examples/white_paper_experiment/README.md
- use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
- use_case_examples/white_paper_experiment/checkpoints/MNIST/MLP_20/fp32/MNIST_fp32_state_dict.pt
- use_case_examples/white_paper_experiment/checkpoints/MNIST/MLP_50/fp32/MNIST_fp32_state_dict.pt
- use_case_examples/white_paper_experiment/requirements.txt
- use_case_examples/white_paper_experiment/utils_experiments.py
cc @kcelia 
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4380
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4297
> Add whitepaper experiments

- tests/pandas/test_pandas.py
this small flaky test made the weekly and other PRs) sometime fail : https://github.com/zama-ai/concrete-ml/actions/runs/9414309379/job/25933015157
> chore: fix pandas flaky test

- src/concrete/ml/deployment/fhe_client_server.py
- src/concrete/ml/torch/hybrid_model.py
- use_case_examples/hybrid_model/compile_hybrid_llm.py
- use_case_examples/hybrid_model/requirements.txt
closes https://github.com/zama-ai/concrete-ml-internal/issues/4525
closes https://github.com/zama-ai/concrete-ml-internal/issues/2498
ref https://github.com/zama-ai/concrete-ml-internal/issues/4525
> chore: improvement hybrid deployment

- src/concrete/ml/torch/hybrid_model.py
- tests/torch/test_hybrid_converter.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/3905
cc @RomanBredehoft
> chore: fix hybrid models

- docs/tutorials/showcase.md
Add 2 new resources to the doc.
> docs: update resources

- src/concrete/ml/pytest/utils.py
- tests/common/test_serialization.py
thanks @jfrery for finding this out
> chore: fix test_serialization_type

- use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
Small clarifications in the WP notebook
> chore: minor clarifications in the WP notebook

- src/concrete/ml/onnx/convert.py
- src/concrete/ml/onnx/onnx_utils.py
- tests/onnx/test_onnx_utils.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4553
needed for big matrices in llms
> fix: protobuf 2gb limit when checking onnx

- Makefile
I am not able to reproduce the issue I have had, certainly the workaround is not needed
closes #https://github.com/zama-ai/concrete-ml-internal/issues/4562
> chore: this workaround was actually not needed

- script/make_utils/check_installation_with_all_python.sh
- script/make_utils/pytest_pypi_cml.sh
without this, weekly tests fail : https://github.com/zama-ai/concrete-ml/actions/runs/10239586387/job/28325426025
> chore: fix wheel tests

- src/concrete/ml/torch/hybrid_model.py
- tests/torch/test_hybrid_converter.py
Close https://github.com/zama-ai/concrete-ml-internal/issues/4571
> chore: change save_and_clear_private_info to consider brevitas models

- src/concrete/ml/torch/hybrid_model.py
the other issue is closed so better to link this one instead cc @kcelia
> chore: change fixme issue link for Hybrid's save circuit issue

- tests/quantization/test_quantized_ops.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4563
> chore: fix flaky quantized div

- src/concrete/ml/torch/hybrid_model.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4579
> chore: add forward method to hybrid model

- docs/SUMMARY.md
- docs/deep-learning/lora_training.md
Explains the LORA functionality added by #823
> docs: add encrypted fine-tuning documentation

- src/concrete/ml/onnx/onnx_utils.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4611
> chore: fix_coverage

- docs/deep-learning/lora_training.md
- docs/guides/using_gpu.md
mirror the 1.7 doc fixes from #908
> fix: port 1.7 doc changes to main

- docs/advanced_examples/ExperimentPrivacyTreePaper.ipynb
closes https://github.com/zama-ai/concrete-ml-internal/issues/4646
> chore: fix weekly bool numpy

- .github/workflows/continuous-integration.yaml
ref https://github.com/zama-ai/concrete-ml-internal/issues/4649
> chore: enforce commit signing for pr

- .github/workflows/continuous-integration.yaml
closes https://github.com/zama-ai/concrete-ml-internal/issues/4653
> chore: do not run commit signature check on weekly / release

- src/concrete/ml/deployment/fhe_client_server.py
This part is still very complicated to use. Clarifying a bit but I think it's not sufficient and would deserve a re-design.
> chore: clarifying a bit the version problems

- tests/torch/test_hybrid_converter.py
Dup of #928 authored with signed commit
> fix: propagate glwe config on hybrid mlp unit test

- .github/workflows/continuous-integration.yaml
closes https://github.com/zama-ai/concrete-ml-internal/issues/4674
> chore: fix flaky making CI pass

- tests/torch/test_hybrid_converter.py
hopefully the last change for the weekly
> chore: fix flaky for weekly

- use_case_examples/resnet/requirements.txt
I spotted it during the hackathon event.
> add missing packages in resnet18 usecase

- deps_licenses/licenses_linux_user.txt
- deps_licenses/licenses_linux_user.txt.md5
- deps_licenses/licenses_mac_intel_user.txt
- deps_licenses/licenses_mac_intel_user.txt.md5
- deps_licenses/licenses_mac_silicon_user.txt
- deps_licenses/licenses_mac_silicon_user.txt.md5
- docker/release_resources/release_requirements.txt
- poetry.lock
- pyproject.toml
- use_case_examples/lora_finetuning/requirements.txt
closes https://github.com/zama-ai/concrete-ml-internal/issues/4660
> chore: remove old opencv from release requirements

- .github/workflows/continuous-integration.yaml
- tests/sklearn/test_sklearn_models.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4697
closes https://github.com/zama-ai/concrete-ml-internal/issues/4683
> chore: fix py>38 tests

- src/concrete/ml/common/serialization/decoder.py
- tests/sklearn/test_sklearn_models.py
closes https://github.com/zama-ai/concrete-ml-internal/issues/4694
> chore: fix sklearn serialization with skops

- docker/Dockerfile.dev
- docker/Dockerfile.release
- use_case_examples/deployment/breast_cancer/Dockerfile.client
- use_case_examples/deployment/breast_cancer/Dockerfile.train
- use_case_examples/deployment/cifar/Dockerfile.client
- use_case_examples/deployment/cifar/Dockerfile.compile
- use_case_examples/deployment/sentiment_analysis/Dockerfile.client
- use_case_examples/deployment/sentiment_analysis/Dockerfile.train
- use_case_examples/deployment/server/Dockerfile.server
Solve the vulnerabilities detected by Trivy, specifically misconfigurations in Dockerfiles.
The misconfig [DS026](https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0026/) about `Add HEALTHCHECK instruction in your Dockerfile` are ignored using [Trivy Ignore File](https://trivy.dev/dev/docs/configuration/filtering/).
The vuln [CVE-2024-5206](https://avd.aquasec.com/nvd/2024/cve-2024-5206/) about `Vulnerable scikit-learn in poetry.lock` has been fixed by updating `scikit-learn` to `1.5.0` in the `pyproject.toml`file.
> Fixes vulns detected by trivy

- script/actions_utils/generate_test_matrix.py
- tests/common/test_serialization.py
Removes some fix-mes and applies the appropriate fix.
Thanks @RomanBredehoft
> fix: outdated fixmes

- use_case_examples/deployment/cifar/build_docker_client_image.py
closes https://github.com/zama-ai/concrete-ml/issues/936
> chore: add docker build python script to cifar deployment
